services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable    
    restart: unless-stopped
    #network_mode: host
    privileged: true
    ports:
      - 8123:8123
    volumes:
      - ./homeassistant:/config
      - /var/run/dbus/:/var/run/dbus/:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    networks:
      - smarthome

  whisper:
    container_name: whisper
    image: lscr.io/linuxserver/faster-whisper:latest
    restart: unless-stopped
    ports:
      - 10300:10300
    volumes:
      - ./local-assist-pipeline/whisper:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WHISPER_MODEL=tiny-int8
      - WHISPER_BEAM=1 #optional
      - WHISPER_LANG=fr #optional    
    networks:
      - smarthome

  piper:
    container_name: piper
    image: lscr.io/linuxserver/piper:latest
    restart: unless-stopped
    ports:
      - 10200:10200    
    volumes:
      - ./local-assist-pipeline/piper:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PIPER_VOICE=fr_FR-siwis-medium # https://huggingface.co/rhasspy/piper-voices/tree/main/fr/fr_FR
      - PIPER_LENGTH=1.0 #optional
      - PIPER_NOISE=0.667 #optional
      - PIPER_NOISEW=0.333 #optional
      - PIPER_SPEAKER=0 #optional
      - PIPER_PROCS=1 #optional
    networks:
      - smarthome

  snowboy:
    container_name: snowboy
    image: rhasspy/wyoming-snowboy
    restart: unless-stopped
    ports:
      - 10400:10400
    command: >
      --uri 'tcp://0.0.0.0:10400'
      --custom-model-dir /custom
    volumes:
      - ./local-assist-pipeline/snowboy/data:/data
      - ./local-assist-pipeline/snowboy/models:/custom
    networks:
      - smarthome
  
  snowboy-seasalt:
    container_name: snowboy-seasalt
    image: rhasspy/snowboy-seasalt
    restart: unless-stopped
    ports:
      - 8888:8000
    networks:
      - smarthome
  # docker run -it -p 8000:8000 rhasspy/snowboy-seasalt

networks:
  smarthome:
    name: smarthome
    driver: bridge
    ipam:
      config:
        - subnet: "172.40.0.0/16"
          gateway: "172.40.0.1"
    